export interface Track {
    index: number;
    src: string;
    title: string;
    cover: string;
    peaks: number[];
}

export const tracks: Record<string, Track> = {
    interference: {
        index: 0,
        src: '/music/interference.mp3',
        title: 'Вмешательство',
        cover: '/images/covers/interference_cover.jpeg',
        peaks: [
            0.6,
            0.7,
            0.8,
            0.7,
            0.5,
            0.8,
            0.8,
            0.9,
            1,
            1,
            0.9,
            0.7,
            0.8,
            0.6,
            0.7,
            0.5,
            0.5,
            0.5,
            0.7,
            0.8,
            0.9,
            0.9,
            0.8,
            0.5,
            1,
            1,
            0.9,
            0.7,
            0.5,
            0.7,
            0.8,
            0.9,
        ]
    },
    ii: {
        index: 1,
        src: '/music/II.mp3',
        title: 'II',
        cover: '/images/covers/ii_cover.jpeg',
        peaks: [
            0.6,
            0.7,
            0.8,
            0.7,
            0.5,
            0.8,
            0.8,
            0.9,
            1,
            1,
            0.9,
            0.7,
            0.8,
            0.6,
            0.7,
            0.5,
            0.5,
            0.5,
            0.7,
            0.8,
            0.9,
            0.9,
            0.8,
            0.5,
            1,
            1,
            0.9,
            0.7,
            0.5,
            0.7,
            0.8,
            0.9,
        ]
    },
    radioDream: {
        index: 2,
        src: '/music/radiodream.mp3',
        title: 'Радиомечта',
        cover: '/images/covers/radiodream_cover.jpeg',
        peaks: [
            0.6,
            0.7,
            0.8,
            0.7,
            0.5,
            0.8,
            0.8,
            0.9,
            1,
            1,
            0.9,
            0.7,
            0.8,
            0.6,
            0.7,
            0.5,
            0.5,
            0.5,
            0.7,
            0.8,
            0.9,
            0.9,
            0.8,
            0.5,
            1,
            1,
            0.9,
            0.7,
            0.5,
            0.7,
            0.8,
            0.9,
        ]
    }
};

export type Tracks = typeof tracks;
export type TrackId = keyof Tracks;
