export interface Track {
    index: number;
    src: string;
    title: string;
    cover: string;
    duration: number;
    peaks: number[];
}

export const tracks: Record<string, Track> = {
    interference: {
        index: 0,
        src: '/music/interference.mp3',
        title: 'Вмешательство',
        cover: 'interference_cover.jpeg',
        duration: 377,
        peaks: [
            0.6,
            0.7,
            0.8,
            0.7,
            0.5,
            0.8,
            0.8,
            0.9,
            1,
            1,
            0.9,
            0.7,
            0.8,
            0.6,
            0.7,
            0.5,
            0.5,
            0.5,
            0.7,
            0.8,
            0.9,
            0.9,
            0.8,
            0.5,
            1,
            1,
            0.9,
            0.7,
            0.5,
            0.7,
            0.8,
            0.9,
        ]
    },
    ii: {
        index: 1,
        src: '/music/II.mp3',
        title: 'II',
        cover: 'ii_cover.jpeg',
        duration: 275,
        peaks: [
            0.6,
            0.7,
            0.8,
            0.7,
            0.5,
            0.8,
            0.8,
            0.9,
            1,
            1,
            0.9,
            0.7,
            0.8,
            0.6,
            0.7,
            0.5,
            0.5,
            0.5,
            0.7,
            0.8,
            0.9,
            0.9,
            0.8,
            0.5,
            1,
            1,
            0.9,
            0.7,
            0.5,
            0.7,
            0.8,
            0.9,
        ]
    },
    radioDream: {
        index: 2,
        src: '/music/radiodream.mp3',
        title: 'Радиомечта',
        cover: 'radiodream_cover.jpeg',
        duration: 473,
        peaks: [
            0.6,
            0.7,
            0.8,
            0.7,
            0.5,
            0.8,
            0.8,
            0.9,
            1,
            1,
            0.9,
            0.7,
            0.8,
            0.6,
            0.7,
            0.5,
            0.5,
            0.5,
            0.7,
            0.8,
            0.9,
            0.9,
            0.8,
            0.5,
            1,
            1,
            0.9,
            0.7,
            0.5,
            0.7,
            0.8,
            0.9,
        ]
    }
};

export type Tracks = typeof tracks;
export type TrackId = keyof Tracks;
